import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/Navbar";



export const metadata: Metadata = {
  title: "NextJS Eco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
